[main]
ip_address: 192.168.1.27
id: 1
width: 1200
height: 825
x_offset: 2200
y_offset: 0
rotation: 180
grey_monochrome_threshold: 190
sleep_time: 10
refresh_every_x_frames: 0
draws_conf:
    { "draw_list": [
        {"type": "black_and_white", "rmt_high_times": [120]}
     ]
    }
enable_skipping: 0
epd_skip_threshold: 100
mode: monochrome
color: 1.0
contrast: 1
brightness: 1.0
sharpness: 1.0
invert: 125
selective_invert: 0
enhance_before_greyscale: 0
selective_compression: 1
do_full_refresh: 0
refresh_on_startup: 2
draw_black_on_startup: 0
esp32_multithread:0
with_cv2:0
polarize_text:1
fill_blacks:1
