[main]
ip_address: 192.168.1.45
id: 1
width: 1200
height: 825
x_offset: 1920
y_offset: 1080
rotation: 0
grey_monochrome_threshold: 200
sleep_time: 5
refresh_every_x_frames: 0
framebuffer_cycles: 2
rmt_high_times: {"main": [200, 200], "aux": [10, 20, 30]}
enable_skipping: 1
epd_skip_threshold: 8000
epd_skip_mouse_only: 1
framebuffer_cycles_2: 2
framebuffer_cycles_2_threshold: 76
mode: monochrome
color: 1.0
contrast: 0.5
brightness: 1.0
sharpness: 1.0
invert: 130
selective_invert: 1
polarize: 2.0,130,off
enhance_before_greyscale: 0
selective_compression: 1
nb_chunks:1
do_full_refresh: 0
draw_white_first: 0
refresh_on_startup: 2
esp32_multithread:1
