[main]
ip_address: 192.168.1.29
id: 1
width: 1200
height: 825
x_offset: 1920
y_offset: 0
rotation: 180
grey_monochrome_threshold: 200
sleep_time: 10
refresh_every_x_frames: 0
draws_conf: {
    "draw_list": [
        {"type": "black_and_white", "rmt_high_times": [100, 100, 100, 100, 100]}
     ]
     }
enable_skipping: 1
epd_skip_threshold: 100
epd_skip_mouse_only: 1
mode: monochrome
color: 1.0
contrast: 0.5
brightness: 1.0
sharpness: 1.0
invert: 130
selective_invert: 1
polarize: 2.0,130,off
enhance_before_greyscale: 0
selective_compression: 90
do_full_refresh: 0
refresh_on_startup: 3
draw_black_on_startup: 1
esp32_multithread:1
with_cv2:0